apiVersion: v1
kind: Secret
metadata:
  name: freedb-admin-secret
  namespace: default
type: Opaque
stringData:
  ## Specify your DB password here
  ## spring_pasword should be same as password specified in store-manager/src/main/resources/db/changelog/user.sql
  oracle_pwd: "<enter_sysadmin_password>"
  spring_user: "store"
  spring_pasword: "<enter_application_user_password>"
  liquibase_user: "SYS AS SYSDBA"
---
apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: freedb-sample
  namespace: default
spec:
  sid: FREE
  edition: free
  adminPassword:
    secretName: freedb-admin-secret
  image:
    pullFrom: container-registry.oracle.com/database/free:latest
    prebuiltDB: true
  persistence:
    size: 20Gi
    storageClass: "standard"
    accessMode: "ReadWriteOnce"
  replicas: 1